using System.Collections.Generic;
using System.Linq;

namespace Common
{
    public class Languages
    {/*
        private static readonly Languages instance = new Languages();

        // Explicit static constructor to tell C# compiler
        // not to mark type as beforefieldinit
        static Languages()
        {
        }

        private Languages()
        {
        }

        public static Languages Instance
        {
            get
            {
                return instance;
            }
        }
        */
        public static List<LanguageObject> Iso639 =
            new List<LanguageObject>
                    {
                        new LanguageObject { Name = "Romanian; Moldavian; Moldovan", Abr2 ="ro", Abr3a = "rum", Abr3b = "ron" },
                        new LanguageObject { Name = "Dutch; Flemish", Abr2 ="nl", Abr3a = "dut", Abr3b = "nld" },
                        new LanguageObject { Name = "English", Abr2 ="en", Abr3a = "eng", Abr3b = "" },

                        new LanguageObject { Name = "Abkhazian", Abr2 ="ab", Abr3a = "abk", Abr3b = "" },
                        new LanguageObject { Name = "Achinese", Abr2 ="", Abr3a = "ace", Abr3b = "" },
                        new LanguageObject { Name = "Acoli", Abr2 ="", Abr3a = "ach", Abr3b = "" },
                        new LanguageObject { Name = "Adangme", Abr2 ="", Abr3a = "ada", Abr3b = "" },
                        new LanguageObject { Name = "Adyghe; Adygei", Abr2 ="", Abr3a = "ady", Abr3b = "" },
                        new LanguageObject { Name = "Afar", Abr2 ="aa", Abr3a = "aar", Abr3b = "" },
                        new LanguageObject { Name = "Afrihili", Abr2 ="", Abr3a = "afh", Abr3b = "" },
                        new LanguageObject { Name = "Afrikaans", Abr2 ="af", Abr3a = "afr", Abr3b = "" },
                        new LanguageObject { Name = "Afro-Asiatic languages", Abr2 ="", Abr3a = "afa", Abr3b = "" },
                        new LanguageObject { Name = "Ainu", Abr2 ="", Abr3a = "ain", Abr3b = "" },
                        new LanguageObject { Name = "Akan", Abr2 ="ak", Abr3a = "aka", Abr3b = "" },
                        new LanguageObject { Name = "Akkadian", Abr2 ="", Abr3a = "akk", Abr3b = "" },
                        new LanguageObject { Name = "Albanian", Abr2 ="sq", Abr3a = "alb", Abr3b = "sqi" },
                        new LanguageObject { Name = "Aleut", Abr2 ="", Abr3a = "ale", Abr3b = "" },
                        new LanguageObject { Name = "Algonquian languages", Abr2 ="", Abr3a = "alg", Abr3b = "" },
                        new LanguageObject { Name = "Altaic languages", Abr2 ="", Abr3a = "tut", Abr3b = "" },
                        new LanguageObject { Name = "Amharic", Abr2 ="am", Abr3a = "amh", Abr3b = "" },
                        new LanguageObject { Name = "Angika", Abr2 ="", Abr3a = "anp", Abr3b = "" },
                        new LanguageObject { Name = "Apache languages", Abr2 ="", Abr3a = "apa", Abr3b = "" },
                        new LanguageObject { Name = "Arabic", Abr2 ="ar", Abr3a = "ara", Abr3b = "" },
                        new LanguageObject { Name = "Aragonese", Abr2 ="an", Abr3a = "arg", Abr3b = "" },
                        new LanguageObject { Name = "Arapaho", Abr2 ="", Abr3a = "arp", Abr3b = "" },
                        new LanguageObject { Name = "Arawak", Abr2 ="", Abr3a = "arw", Abr3b = "" },
                        new LanguageObject { Name = "Armenian", Abr2 ="hy", Abr3a = "arm", Abr3b = "hye" },
                        new LanguageObject { Name = "Aromanian; Arumanian; Macedo-Romanian", Abr2 ="", Abr3a = "rup", Abr3b = "" },
                        new LanguageObject { Name = "Artificial languages", Abr2 ="", Abr3a = "art", Abr3b = "" },
                        new LanguageObject { Name = "Assamese", Abr2 ="as", Abr3a = "asm", Abr3b = "" },
                        new LanguageObject { Name = "Asturian; Bable; Leonese; Asturleonese", Abr2 ="", Abr3a = "ast", Abr3b = "" },
                        new LanguageObject { Name = "Athapascan languages", Abr2 ="", Abr3a = "ath", Abr3b = "" },
                        new LanguageObject { Name = "Australian languages", Abr2 ="", Abr3a = "aus", Abr3b = "" },
                        new LanguageObject { Name = "Austronesian languages", Abr2 ="", Abr3a = "map", Abr3b = "" },
                        new LanguageObject { Name = "Avaric", Abr2 ="av", Abr3a = "ava", Abr3b = "" },
                        new LanguageObject { Name = "Avestan", Abr2 ="ae", Abr3a = "ave", Abr3b = "" },
                        new LanguageObject { Name = "Awadhi", Abr2 ="", Abr3a = "awa", Abr3b = "" },
                        new LanguageObject { Name = "Aymara", Abr2 ="ay", Abr3a = "aym", Abr3b = "" },
                        new LanguageObject { Name = "Azerbaijani", Abr2 ="az", Abr3a = "aze", Abr3b = "" },
                        new LanguageObject { Name = "Balinese", Abr2 ="", Abr3a = "ban", Abr3b = "" },
                        new LanguageObject { Name = "Baltic languages", Abr2 ="", Abr3a = "bat", Abr3b = "" },
                        new LanguageObject { Name = "Baluchi", Abr2 ="", Abr3a = "bal", Abr3b = "" },
                        new LanguageObject { Name = "Bambara", Abr2 ="bm", Abr3a = "bam", Abr3b = "" },
                        new LanguageObject { Name = "Bamileke languages", Abr2 ="", Abr3a = "bai", Abr3b = "" },
                        new LanguageObject { Name = "Banda languages", Abr2 ="", Abr3a = "bad", Abr3b = "" },
                        new LanguageObject { Name = "Bantu languages", Abr2 ="", Abr3a = "bnt", Abr3b = "" },
                        new LanguageObject { Name = "Basa", Abr2 ="", Abr3a = "bas", Abr3b = "" },
                        new LanguageObject { Name = "Bashkir", Abr2 ="ba", Abr3a = "bak", Abr3b = "" },
                        new LanguageObject { Name = "Basque", Abr2 ="eu", Abr3a = "baq", Abr3b = "eus" },
                        new LanguageObject { Name = "Batak languages", Abr2 ="", Abr3a = "btk", Abr3b = "" },
                        new LanguageObject { Name = "Beja; Bedawiyet", Abr2 ="", Abr3a = "bej", Abr3b = "" },
                        new LanguageObject { Name = "Belarusian", Abr2 ="be", Abr3a = "bel", Abr3b = "" },
                        new LanguageObject { Name = "Bemba", Abr2 ="", Abr3a = "bem", Abr3b = "" },
                        new LanguageObject { Name = "Bengali", Abr2 ="bn", Abr3a = "ben", Abr3b = "" },
                        new LanguageObject { Name = "Berber languages", Abr2 ="", Abr3a = "ber", Abr3b = "" },
                        new LanguageObject { Name = "Bhojpuri", Abr2 ="", Abr3a = "bho", Abr3b = "" },
                        new LanguageObject { Name = "Bihari languages", Abr2 ="bh", Abr3a = "bih", Abr3b = "" },
                        new LanguageObject { Name = "Bikol", Abr2 ="", Abr3a = "bik", Abr3b = "" },
                        new LanguageObject { Name = "Bini; Edo", Abr2 ="", Abr3a = "bin", Abr3b = "" },
                        new LanguageObject { Name = "Bislama", Abr2 ="bi", Abr3a = "bis", Abr3b = "" },
                        new LanguageObject { Name = "Blin; Bilin", Abr2 ="", Abr3a = "byn", Abr3b = "" },
                        new LanguageObject { Name = "Blissymbols; Blissymbolics; Bliss", Abr2 ="", Abr3a = "zbl", Abr3b = "" },
                        new LanguageObject { Name = "Bokmål, Norwegian; Norwegian Bokmål", Abr2 ="nb", Abr3a = "nob", Abr3b = "" },
                        new LanguageObject { Name = "Bosnian", Abr2 ="bs", Abr3a = "bos", Abr3b = "" },
                        new LanguageObject { Name = "Braj", Abr2 ="", Abr3a = "bra", Abr3b = "" },
                        new LanguageObject { Name = "Breton", Abr2 ="br", Abr3a = "bre", Abr3b = "" },
                        new LanguageObject { Name = "Buginese", Abr2 ="", Abr3a = "bug", Abr3b = "" },
                        new LanguageObject { Name = "Bulgarian", Abr2 ="bg", Abr3a = "bul", Abr3b = "" },
                        new LanguageObject { Name = "Buriat", Abr2 ="", Abr3a = "bua", Abr3b = "" },
                        new LanguageObject { Name = "Burmese", Abr2 ="my", Abr3a = "bur", Abr3b = "mya" },
                        new LanguageObject { Name = "Caddo", Abr2 ="", Abr3a = "cad", Abr3b = "" },
                        new LanguageObject { Name = "Catalan; Valencian", Abr2 ="ca", Abr3a = "cat", Abr3b = "" },
                        new LanguageObject { Name = "Caucasian languages", Abr2 ="", Abr3a = "cau", Abr3b = "" },
                        new LanguageObject { Name = "Cebuano", Abr2 ="", Abr3a = "ceb", Abr3b = "" },
                        new LanguageObject { Name = "Celtic languages", Abr2 ="", Abr3a = "cel", Abr3b = "" },
                        new LanguageObject { Name = "Central American Indian languages", Abr2 ="", Abr3a = "cai", Abr3b = "" },
                        new LanguageObject { Name = "Central Khmer", Abr2 ="km", Abr3a = "khm", Abr3b = "" },
                        new LanguageObject { Name = "Chagatai", Abr2 ="", Abr3a = "chg", Abr3b = "" },
                        new LanguageObject { Name = "Chamic languages", Abr2 ="", Abr3a = "cmc", Abr3b = "" },
                        new LanguageObject { Name = "Chamorro", Abr2 ="ch", Abr3a = "cha", Abr3b = "" },
                        new LanguageObject { Name = "Chechen", Abr2 ="ce", Abr3a = "che", Abr3b = "" },
                        new LanguageObject { Name = "Cherokee", Abr2 ="", Abr3a = "chr", Abr3b = "" },
                        new LanguageObject { Name = "Cheyenne", Abr2 ="", Abr3a = "chy", Abr3b = "" },
                        new LanguageObject { Name = "Chibcha", Abr2 ="", Abr3a = "chb", Abr3b = "" },
                        new LanguageObject { Name = "Chichewa; Chewa; Nyanja", Abr2 ="ny", Abr3a = "nya", Abr3b = "" },
                        new LanguageObject { Name = "Chinese", Abr2 ="zh", Abr3a = "chi", Abr3b = "zho" },
                        new LanguageObject { Name = "Chinook jargon", Abr2 ="", Abr3a = "chn", Abr3b = "" },
                        new LanguageObject { Name = "Chipewyan; Dene Suline", Abr2 ="", Abr3a = "chp", Abr3b = "" },
                        new LanguageObject { Name = "Choctaw", Abr2 ="", Abr3a = "cho", Abr3b = "" },
                        new LanguageObject { Name = "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", Abr2 ="cu", Abr3a = "chu", Abr3b = "" },
                        new LanguageObject { Name = "Chuukese", Abr2 ="", Abr3a = "chk", Abr3b = "" },
                        new LanguageObject { Name = "Chuvash", Abr2 ="cv", Abr3a = "chv", Abr3b = "" },
                        new LanguageObject { Name = "Classical Newari; Old Newari; Classical Nepal Bhasa", Abr2 ="", Abr3a = "nwc", Abr3b = "" },
                        new LanguageObject { Name = "Classical Syriac", Abr2 ="", Abr3a = "syc", Abr3b = "" },
                        new LanguageObject { Name = "Coptic", Abr2 ="", Abr3a = "cop", Abr3b = "" },
                        new LanguageObject { Name = "Cornish", Abr2 ="kw", Abr3a = "cor", Abr3b = "" },
                        new LanguageObject { Name = "Corsican", Abr2 ="co", Abr3a = "cos", Abr3b = "" },
                        new LanguageObject { Name = "Cree", Abr2 ="cr", Abr3a = "cre", Abr3b = "" },
                        new LanguageObject { Name = "Creek", Abr2 ="", Abr3a = "mus", Abr3b = "" },
                        new LanguageObject { Name = "Creoles and pidgins", Abr2 ="", Abr3a = "crp", Abr3b = "" },
                        new LanguageObject { Name = "Creoles and pidgins, English based", Abr2 ="", Abr3a = "cpe", Abr3b = "" },
                        new LanguageObject { Name = "Creoles and pidgins, French-based", Abr2 ="", Abr3a = "cpf", Abr3b = "" },
                        new LanguageObject { Name = "Creoles and pidgins, Portuguese-based", Abr2 ="", Abr3a = "cpp", Abr3b = "" },
                        new LanguageObject { Name = "Crimean Tatar; Crimean Turkish", Abr2 ="", Abr3a = "crh", Abr3b = "" },
                        new LanguageObject { Name = "Croatian", Abr2 ="hr", Abr3a = "hrv", Abr3b = "" },
                        new LanguageObject { Name = "Cushitic languages", Abr2 ="", Abr3a = "cus", Abr3b = "" },
                        new LanguageObject { Name = "Czech", Abr2 ="cs", Abr3a = "cze", Abr3b = "ces" },
                        new LanguageObject { Name = "Dakota", Abr2 ="", Abr3a = "dak", Abr3b = "" },
                        new LanguageObject { Name = "Danish", Abr2 ="da", Abr3a = "dan", Abr3b = "" },
                        new LanguageObject { Name = "Dargwa", Abr2 ="", Abr3a = "dar", Abr3b = "" },
                        new LanguageObject { Name = "Delaware", Abr2 ="", Abr3a = "del", Abr3b = "" },
                        new LanguageObject { Name = "Dinka", Abr2 ="", Abr3a = "din", Abr3b = "" },
                        new LanguageObject { Name = "Divehi; Dhivehi; Maldivian", Abr2 ="dv", Abr3a = "div", Abr3b = "" },
                        new LanguageObject { Name = "Dogri", Abr2 ="", Abr3a = "doi", Abr3b = "" },
                        new LanguageObject { Name = "Dogrib", Abr2 ="", Abr3a = "dgr", Abr3b = "" },
                        new LanguageObject { Name = "Dravidian languages", Abr2 ="", Abr3a = "dra", Abr3b = "" },
                        new LanguageObject { Name = "Duala", Abr2 ="", Abr3a = "dua", Abr3b = "" },
                        new LanguageObject { Name = "Dutch, Middle (ca.1050-1350)", Abr2 ="", Abr3a = "dum", Abr3b = "" },
                        //new LanguageObject { Name = "Dutch; Flemish", Abr2 ="nl", Abr3a = "dut", Abr3b = "nld" },
                        new LanguageObject { Name = "Dyula", Abr2 ="", Abr3a = "dyu", Abr3b = "" },
                        new LanguageObject { Name = "Dzongkha", Abr2 ="dz", Abr3a = "dzo", Abr3b = "" },
                        new LanguageObject { Name = "Eastern Frisian", Abr2 ="", Abr3a = "frs", Abr3b = "" },
                        new LanguageObject { Name = "Efik", Abr2 ="", Abr3a = "efi", Abr3b = "" },
                        new LanguageObject { Name = "Egyptian (Ancient)", Abr2 ="", Abr3a = "egy", Abr3b = "" },
                        new LanguageObject { Name = "Ekajuk", Abr2 ="", Abr3a = "eka", Abr3b = "" },
                        new LanguageObject { Name = "Elamite", Abr2 ="", Abr3a = "elx", Abr3b = "" },
                        //new LanguageObject { Name = "English", Abr2 ="en", Abr3a = "eng", Abr3b = "" },
                        new LanguageObject { Name = "English, Middle (1100-1500)", Abr2 ="", Abr3a = "enm", Abr3b = "" },
                        new LanguageObject { Name = "English, Old (ca.450-1100)", Abr2 ="", Abr3a = "ang", Abr3b = "" },
                        new LanguageObject { Name = "Erzya", Abr2 ="", Abr3a = "myv", Abr3b = "" },
                        new LanguageObject { Name = "Esperanto", Abr2 ="eo", Abr3a = "epo", Abr3b = "" },
                        new LanguageObject { Name = "Estonian", Abr2 ="et", Abr3a = "est", Abr3b = "" },
                        new LanguageObject { Name = "Ewe", Abr2 ="ee", Abr3a = "ewe", Abr3b = "" },
                        new LanguageObject { Name = "Ewondo", Abr2 ="", Abr3a = "ewo", Abr3b = "" },
                        new LanguageObject { Name = "Fang", Abr2 ="", Abr3a = "fan", Abr3b = "" },
                        new LanguageObject { Name = "Fanti", Abr2 ="", Abr3a = "fat", Abr3b = "" },
                        new LanguageObject { Name = "Faroese", Abr2 ="fo", Abr3a = "fao", Abr3b = "" },
                        new LanguageObject { Name = "Fijian", Abr2 ="fj", Abr3a = "fij", Abr3b = "" },
                        new LanguageObject { Name = "Filipino; Pilipino", Abr2 ="", Abr3a = "fil", Abr3b = "" },
                        new LanguageObject { Name = "Finnish", Abr2 ="fi", Abr3a = "fin", Abr3b = "" },
                        new LanguageObject { Name = "Finno-Ugrian languages", Abr2 ="", Abr3a = "fiu", Abr3b = "" },
                        new LanguageObject { Name = "Fon", Abr2 ="", Abr3a = "fon", Abr3b = "" },
                        new LanguageObject { Name = "French", Abr2 ="fr", Abr3a = "fre", Abr3b = "fra" },
                        new LanguageObject { Name = "French, Middle (ca.1400-1600)", Abr2 ="", Abr3a = "frm", Abr3b = "" },
                        new LanguageObject { Name = "French, Old (842-ca.1400)", Abr2 ="", Abr3a = "fro", Abr3b = "" },
                        new LanguageObject { Name = "Friulian", Abr2 ="", Abr3a = "fur", Abr3b = "" },
                        new LanguageObject { Name = "Fulah", Abr2 ="ff", Abr3a = "ful", Abr3b = "" },
                        new LanguageObject { Name = "Ga", Abr2 ="", Abr3a = "gaa", Abr3b = "" },
                        new LanguageObject { Name = "Gaelic; Scottish Gaelic", Abr2 ="gd", Abr3a = "gla", Abr3b = "" },
                        new LanguageObject { Name = "Galibi Carib", Abr2 ="", Abr3a = "car", Abr3b = "" },
                        new LanguageObject { Name = "Galician", Abr2 ="gl", Abr3a = "glg", Abr3b = "" },
                        new LanguageObject { Name = "Ganda", Abr2 ="lg", Abr3a = "lug", Abr3b = "" },
                        new LanguageObject { Name = "Gayo", Abr2 ="", Abr3a = "gay", Abr3b = "" },
                        new LanguageObject { Name = "Gbaya", Abr2 ="", Abr3a = "gba", Abr3b = "" },
                        new LanguageObject { Name = "Geez", Abr2 ="", Abr3a = "gez", Abr3b = "" },
                        new LanguageObject { Name = "Georgian", Abr2 ="ka", Abr3a = "geo", Abr3b = "kat" },
                        new LanguageObject { Name = "German", Abr2 ="de", Abr3a = "ger", Abr3b = "deu" },
                        new LanguageObject { Name = "German, Middle High (ca.1050-1500)", Abr2 ="", Abr3a = "gmh", Abr3b = "" },
                        new LanguageObject { Name = "German, Old High (ca.750-1050)", Abr2 ="", Abr3a = "goh", Abr3b = "" },
                        new LanguageObject { Name = "Germanic languages", Abr2 ="", Abr3a = "gem", Abr3b = "" },
                        new LanguageObject { Name = "Gilbertese", Abr2 ="", Abr3a = "gil", Abr3b = "" },
                        new LanguageObject { Name = "Gondi", Abr2 ="", Abr3a = "gon", Abr3b = "" },
                        new LanguageObject { Name = "Gorontalo", Abr2 ="", Abr3a = "gor", Abr3b = "" },
                        new LanguageObject { Name = "Gothic", Abr2 ="", Abr3a = "got", Abr3b = "" },
                        new LanguageObject { Name = "Grebo", Abr2 ="", Abr3a = "grb", Abr3b = "" },
                        new LanguageObject { Name = "Greek, Ancient (to 1453)", Abr2 ="", Abr3a = "grc", Abr3b = "" },
                        new LanguageObject { Name = "Greek, Modern (1453-)", Abr2 ="el", Abr3a = "gre", Abr3b = "ell" },
                        new LanguageObject { Name = "Guarani", Abr2 ="gn", Abr3a = "grn", Abr3b = "" },
                        new LanguageObject { Name = "Gujarati", Abr2 ="gu", Abr3a = "guj", Abr3b = "" },
                        new LanguageObject { Name = "Gwich'in", Abr2 ="", Abr3a = "gwi", Abr3b = "" },
                        new LanguageObject { Name = "Haida", Abr2 ="", Abr3a = "hai", Abr3b = "" },
                        new LanguageObject { Name = "Haitian; Haitian Creole", Abr2 ="ht", Abr3a = "hat", Abr3b = "" },
                        new LanguageObject { Name = "Hausa", Abr2 ="ha", Abr3a = "hau", Abr3b = "" },
                        new LanguageObject { Name = "Hawaiian", Abr2 ="", Abr3a = "haw", Abr3b = "" },
                        new LanguageObject { Name = "Hebrew", Abr2 ="he", Abr3a = "heb", Abr3b = "" },
                        new LanguageObject { Name = "Herero", Abr2 ="hz", Abr3a = "her", Abr3b = "" },
                        new LanguageObject { Name = "Hiligaynon", Abr2 ="", Abr3a = "hil", Abr3b = "" },
                        new LanguageObject { Name = "Himachali languages; Western Pahari languages", Abr2 ="", Abr3a = "him", Abr3b = "" },
                        new LanguageObject { Name = "Hindi", Abr2 ="hi", Abr3a = "hin", Abr3b = "" },
                        new LanguageObject { Name = "Hiri Motu", Abr2 ="ho", Abr3a = "hmo", Abr3b = "" },
                        new LanguageObject { Name = "Hittite", Abr2 ="", Abr3a = "hit", Abr3b = "" },
                        new LanguageObject { Name = "Hmong; Mong", Abr2 ="", Abr3a = "hmn", Abr3b = "" },
                        new LanguageObject { Name = "Hungarian", Abr2 ="hu", Abr3a = "hun", Abr3b = "" },
                        new LanguageObject { Name = "Hupa", Abr2 ="", Abr3a = "hup", Abr3b = "" },
                        new LanguageObject { Name = "Iban", Abr2 ="", Abr3a = "iba", Abr3b = "" },
                        new LanguageObject { Name = "Icelandic", Abr2 ="is", Abr3a = "ice", Abr3b = "isl" },
                        new LanguageObject { Name = "Ido", Abr2 ="io", Abr3a = "ido", Abr3b = "" },
                        new LanguageObject { Name = "Igbo", Abr2 ="ig", Abr3a = "ibo", Abr3b = "" },
                        new LanguageObject { Name = "Ijo languages", Abr2 ="", Abr3a = "ijo", Abr3b = "" },
                        new LanguageObject { Name = "Iloko", Abr2 ="", Abr3a = "ilo", Abr3b = "" },
                        new LanguageObject { Name = "Inari Sami", Abr2 ="", Abr3a = "smn", Abr3b = "" },
                        new LanguageObject { Name = "Indic languages", Abr2 ="", Abr3a = "inc", Abr3b = "" },
                        new LanguageObject { Name = "Indo-European languages", Abr2 ="", Abr3a = "ine", Abr3b = "" },
                        new LanguageObject { Name = "Indonesian", Abr2 ="id", Abr3a = "ind", Abr3b = "" },
                        new LanguageObject { Name = "Ingush", Abr2 ="", Abr3a = "inh", Abr3b = "" },
                        new LanguageObject { Name = "Interlingua (International Auxiliary Language Association)", Abr2 ="ia", Abr3a = "ina", Abr3b = "" },
                        new LanguageObject { Name = "Interlingue; Occidental", Abr2 ="ie", Abr3a = "ile", Abr3b = "" },
                        new LanguageObject { Name = "Inuktitut", Abr2 ="iu", Abr3a = "iku", Abr3b = "" },
                        new LanguageObject { Name = "Inupiaq", Abr2 ="ik", Abr3a = "ipk", Abr3b = "" },
                        new LanguageObject { Name = "Iranian languages", Abr2 ="", Abr3a = "ira", Abr3b = "" },
                        new LanguageObject { Name = "Irish", Abr2 ="ga", Abr3a = "gle", Abr3b = "" },
                        new LanguageObject { Name = "Irish, Middle (900-1200)", Abr2 ="", Abr3a = "mga", Abr3b = "" },
                        new LanguageObject { Name = "Irish, Old (to 900)", Abr2 ="", Abr3a = "sga", Abr3b = "" },
                        new LanguageObject { Name = "Iroquoian languages", Abr2 ="", Abr3a = "iro", Abr3b = "" },
                        new LanguageObject { Name = "Italian", Abr2 ="it", Abr3a = "ita", Abr3b = "" },
                        new LanguageObject { Name = "Japanese", Abr2 ="ja", Abr3a = "jpn", Abr3b = "" },
                        new LanguageObject { Name = "Javanese", Abr2 ="jv", Abr3a = "jav", Abr3b = "" },
                        new LanguageObject { Name = "Judeo-Arabic", Abr2 ="", Abr3a = "jrb", Abr3b = "" },
                        new LanguageObject { Name = "Judeo-Persian", Abr2 ="", Abr3a = "jpr", Abr3b = "" },
                        new LanguageObject { Name = "Kabardian", Abr2 ="", Abr3a = "kbd", Abr3b = "" },
                        new LanguageObject { Name = "Kabyle", Abr2 ="", Abr3a = "kab", Abr3b = "" },
                        new LanguageObject { Name = "Kachin; Jingpho", Abr2 ="", Abr3a = "kac", Abr3b = "" },
                        new LanguageObject { Name = "Kalaallisut; Greenlandic", Abr2 ="kl", Abr3a = "kal", Abr3b = "" },
                        new LanguageObject { Name = "Kalmyk; Oirat", Abr2 ="", Abr3a = "xal", Abr3b = "" },
                        new LanguageObject { Name = "Kamba", Abr2 ="", Abr3a = "kam", Abr3b = "" },
                        new LanguageObject { Name = "Kannada", Abr2 ="kn", Abr3a = "kan", Abr3b = "" },
                        new LanguageObject { Name = "Kanuri", Abr2 ="kr", Abr3a = "kau", Abr3b = "" },
                        new LanguageObject { Name = "Kara-Kalpak", Abr2 ="", Abr3a = "kaa", Abr3b = "" },
                        new LanguageObject { Name = "Karachay-Balkar", Abr2 ="", Abr3a = "krc", Abr3b = "" },
                        new LanguageObject { Name = "Karelian", Abr2 ="", Abr3a = "krl", Abr3b = "" },
                        new LanguageObject { Name = "Karen languages", Abr2 ="", Abr3a = "kar", Abr3b = "" },
                        new LanguageObject { Name = "Kashmiri", Abr2 ="ks", Abr3a = "kas", Abr3b = "" },
                        new LanguageObject { Name = "Kashubian", Abr2 ="", Abr3a = "csb", Abr3b = "" },
                        new LanguageObject { Name = "Kawi", Abr2 ="", Abr3a = "kaw", Abr3b = "" },
                        new LanguageObject { Name = "Kazakh", Abr2 ="kk", Abr3a = "kaz", Abr3b = "" },
                        new LanguageObject { Name = "Khasi", Abr2 ="", Abr3a = "kha", Abr3b = "" },
                        new LanguageObject { Name = "Khoisan languages", Abr2 ="", Abr3a = "khi", Abr3b = "" },
                        new LanguageObject { Name = "Khotanese; Sakan", Abr2 ="", Abr3a = "kho", Abr3b = "" },
                        new LanguageObject { Name = "Kikuyu; Gikuyu", Abr2 ="ki", Abr3a = "kik", Abr3b = "" },
                        new LanguageObject { Name = "Kimbundu", Abr2 ="", Abr3a = "kmb", Abr3b = "" },
                        new LanguageObject { Name = "Kinyarwanda", Abr2 ="rw", Abr3a = "kin", Abr3b = "" },
                        new LanguageObject { Name = "Kirghiz; Kyrgyz", Abr2 ="ky", Abr3a = "kir", Abr3b = "" },
                        new LanguageObject { Name = "Klingon; tlhIngan-Hol", Abr2 ="", Abr3a = "tlh", Abr3b = "" },
                        new LanguageObject { Name = "Komi", Abr2 ="kv", Abr3a = "kom", Abr3b = "" },
                        new LanguageObject { Name = "Kongo", Abr2 ="kg", Abr3a = "kon", Abr3b = "" },
                        new LanguageObject { Name = "Konkani", Abr2 ="", Abr3a = "kok", Abr3b = "" },
                        new LanguageObject { Name = "Korean", Abr2 ="ko", Abr3a = "kor", Abr3b = "" },
                        new LanguageObject { Name = "Kosraean", Abr2 ="", Abr3a = "kos", Abr3b = "" },
                        new LanguageObject { Name = "Kpelle", Abr2 ="", Abr3a = "kpe", Abr3b = "" },
                        new LanguageObject { Name = "Kru languages", Abr2 ="", Abr3a = "kro", Abr3b = "" },
                        new LanguageObject { Name = "Kuanyama; Kwanyama", Abr2 ="kj", Abr3a = "kua", Abr3b = "" },
                        new LanguageObject { Name = "Kumyk", Abr2 ="", Abr3a = "kum", Abr3b = "" },
                        new LanguageObject { Name = "Kurdish", Abr2 ="ku", Abr3a = "kur", Abr3b = "" },
                        new LanguageObject { Name = "Kurukh", Abr2 ="", Abr3a = "kru", Abr3b = "" },
                        new LanguageObject { Name = "Kutenai", Abr2 ="", Abr3a = "kut", Abr3b = "" },
                        new LanguageObject { Name = "Ladino", Abr2 ="", Abr3a = "lad", Abr3b = "" },
                        new LanguageObject { Name = "Lahnda", Abr2 ="", Abr3a = "lah", Abr3b = "" },
                        new LanguageObject { Name = "Lamba", Abr2 ="", Abr3a = "lam", Abr3b = "" },
                        new LanguageObject { Name = "Land Dayak languages", Abr2 ="", Abr3a = "day", Abr3b = "" },
                        new LanguageObject { Name = "Lao", Abr2 ="lo", Abr3a = "lao", Abr3b = "" },
                        new LanguageObject { Name = "Latin", Abr2 ="la", Abr3a = "lat", Abr3b = "" },
                        new LanguageObject { Name = "Latvian", Abr2 ="lv", Abr3a = "lav", Abr3b = "" },
                        new LanguageObject { Name = "Lezghian", Abr2 ="", Abr3a = "lez", Abr3b = "" },
                        new LanguageObject { Name = "Limburgan; Limburger; Limburgish", Abr2 ="li", Abr3a = "lim", Abr3b = "" },
                        new LanguageObject { Name = "Lingala", Abr2 ="ln", Abr3a = "lin", Abr3b = "" },
                        new LanguageObject { Name = "Lithuanian", Abr2 ="lt", Abr3a = "lit", Abr3b = "" },
                        new LanguageObject { Name = "Lojban", Abr2 ="", Abr3a = "jbo", Abr3b = "" },
                        new LanguageObject { Name = "Low German; Low Saxon; German, Low; Saxon, Low", Abr2 ="", Abr3a = "nds", Abr3b = "" },
                        new LanguageObject { Name = "Lower Sorbian", Abr2 ="", Abr3a = "dsb", Abr3b = "" },
                        new LanguageObject { Name = "Lozi", Abr2 ="", Abr3a = "loz", Abr3b = "" },
                        new LanguageObject { Name = "Luba-Katanga", Abr2 ="lu", Abr3a = "lub", Abr3b = "" },
                        new LanguageObject { Name = "Luba-Lulua", Abr2 ="", Abr3a = "lua", Abr3b = "" },
                        new LanguageObject { Name = "Luiseno", Abr2 ="", Abr3a = "lui", Abr3b = "" },
                        new LanguageObject { Name = "Lule Sami", Abr2 ="", Abr3a = "smj", Abr3b = "" },
                        new LanguageObject { Name = "Lunda", Abr2 ="", Abr3a = "lun", Abr3b = "" },
                        new LanguageObject { Name = "Luo (Kenya and Tanzania)", Abr2 ="", Abr3a = "luo", Abr3b = "" },
                        new LanguageObject { Name = "Lushai", Abr2 ="", Abr3a = "lus", Abr3b = "" },
                        new LanguageObject { Name = "Luxembourgish; Letzeburgesch", Abr2 ="lb", Abr3a = "ltz", Abr3b = "" },
                        new LanguageObject { Name = "Macedonian", Abr2 ="mk", Abr3a = "mac", Abr3b = "mkd" },
                        new LanguageObject { Name = "Madurese", Abr2 ="", Abr3a = "mad", Abr3b = "" },
                        new LanguageObject { Name = "Magahi", Abr2 ="", Abr3a = "mag", Abr3b = "" },
                        new LanguageObject { Name = "Maithili", Abr2 ="", Abr3a = "mai", Abr3b = "" },
                        new LanguageObject { Name = "Makasar", Abr2 ="", Abr3a = "mak", Abr3b = "" },
                        new LanguageObject { Name = "Malagasy", Abr2 ="mg", Abr3a = "mlg", Abr3b = "" },
                        new LanguageObject { Name = "Malay", Abr2 ="ms", Abr3a = "may", Abr3b = "msa" },
                        new LanguageObject { Name = "Malayalam", Abr2 ="ml", Abr3a = "mal", Abr3b = "" },
                        new LanguageObject { Name = "Maltese", Abr2 ="mt", Abr3a = "mlt", Abr3b = "" },
                        new LanguageObject { Name = "Manchu", Abr2 ="", Abr3a = "mnc", Abr3b = "" },
                        new LanguageObject { Name = "Mandar", Abr2 ="", Abr3a = "mdr", Abr3b = "" },
                        new LanguageObject { Name = "Mandingo", Abr2 ="", Abr3a = "man", Abr3b = "" },
                        new LanguageObject { Name = "Manipuri", Abr2 ="", Abr3a = "mni", Abr3b = "" },
                        new LanguageObject { Name = "Manobo languages", Abr2 ="", Abr3a = "mno", Abr3b = "" },
                        new LanguageObject { Name = "Manx", Abr2 ="gv", Abr3a = "glv", Abr3b = "" },
                        new LanguageObject { Name = "Maori", Abr2 ="mi", Abr3a = "mao", Abr3b = "mri" },
                        new LanguageObject { Name = "Mapudungun; Mapuche", Abr2 ="", Abr3a = "arn", Abr3b = "" },
                        new LanguageObject { Name = "Marathi", Abr2 ="mr", Abr3a = "mar", Abr3b = "" },
                        new LanguageObject { Name = "Mari", Abr2 ="", Abr3a = "chm", Abr3b = "" },
                        new LanguageObject { Name = "Marshallese", Abr2 ="mh", Abr3a = "mah", Abr3b = "" },
                        new LanguageObject { Name = "Marwari", Abr2 ="", Abr3a = "mwr", Abr3b = "" },
                        new LanguageObject { Name = "Masai", Abr2 ="", Abr3a = "mas", Abr3b = "" },
                        new LanguageObject { Name = "Mayan languages", Abr2 ="", Abr3a = "myn", Abr3b = "" },
                        new LanguageObject { Name = "Mende", Abr2 ="", Abr3a = "men", Abr3b = "" },
                        new LanguageObject { Name = "Mi'kmaq; Micmac", Abr2 ="", Abr3a = "mic", Abr3b = "" },
                        new LanguageObject { Name = "Minangkabau", Abr2 ="", Abr3a = "min", Abr3b = "" },
                        new LanguageObject { Name = "Mirandese", Abr2 ="", Abr3a = "mwl", Abr3b = "" },
                        new LanguageObject { Name = "Mohawk", Abr2 ="", Abr3a = "moh", Abr3b = "" },
                        new LanguageObject { Name = "Moksha", Abr2 ="", Abr3a = "mdf", Abr3b = "" },
                        new LanguageObject { Name = "Mon-Khmer languages", Abr2 ="", Abr3a = "mkh", Abr3b = "" },
                        new LanguageObject { Name = "Mongo", Abr2 ="", Abr3a = "lol", Abr3b = "" },
                        new LanguageObject { Name = "Mongolian", Abr2 ="mn", Abr3a = "mon", Abr3b = "" },
                        new LanguageObject { Name = "Mossi", Abr2 ="", Abr3a = "mos", Abr3b = "" },
                        new LanguageObject { Name = "Multiple languages", Abr2 ="", Abr3a = "mul", Abr3b = "" },
                        new LanguageObject { Name = "Munda languages", Abr2 ="", Abr3a = "mun", Abr3b = "" },
                        new LanguageObject { Name = "N'Ko", Abr2 ="", Abr3a = "nqo", Abr3b = "" },
                        new LanguageObject { Name = "Nahuatl languages", Abr2 ="", Abr3a = "nah", Abr3b = "" },
                        new LanguageObject { Name = "Nauru", Abr2 ="na", Abr3a = "nau", Abr3b = "" },
                        new LanguageObject { Name = "Navajo; Navaho", Abr2 ="nv", Abr3a = "nav", Abr3b = "" },
                        new LanguageObject { Name = "Ndebele, North; North Ndebele", Abr2 ="nd", Abr3a = "nde", Abr3b = "" },
                        new LanguageObject { Name = "Ndebele, South; South Ndebele", Abr2 ="nr", Abr3a = "nbl", Abr3b = "" },
                        new LanguageObject { Name = "Ndonga", Abr2 ="ng", Abr3a = "ndo", Abr3b = "" },
                        new LanguageObject { Name = "Neapolitan", Abr2 ="", Abr3a = "nap", Abr3b = "" },
                        new LanguageObject { Name = "Nepal Bhasa; Newari", Abr2 ="", Abr3a = "new", Abr3b = "" },
                        new LanguageObject { Name = "Nepali", Abr2 ="ne", Abr3a = "nep", Abr3b = "" },
                        new LanguageObject { Name = "Nias", Abr2 ="", Abr3a = "nia", Abr3b = "" },
                        new LanguageObject { Name = "Niger-Kordofanian languages", Abr2 ="", Abr3a = "nic", Abr3b = "" },
                        new LanguageObject { Name = "Nilo-Saharan languages", Abr2 ="", Abr3a = "ssa", Abr3b = "" },
                        new LanguageObject { Name = "Niuean", Abr2 ="", Abr3a = "niu", Abr3b = "" },
                        new LanguageObject { Name = "No linguistic content; Not applicable", Abr2 ="", Abr3a = "zxx", Abr3b = "" },
                        new LanguageObject { Name = "Nogai", Abr2 ="", Abr3a = "nog", Abr3b = "" },
                        new LanguageObject { Name = "Norse, Old", Abr2 ="", Abr3a = "non", Abr3b = "" },
                        new LanguageObject { Name = "North American Indian languages", Abr2 ="", Abr3a = "nai", Abr3b = "" },
                        new LanguageObject { Name = "Northern Frisian", Abr2 ="", Abr3a = "frr", Abr3b = "" },
                        new LanguageObject { Name = "Northern Sami", Abr2 ="se", Abr3a = "sme", Abr3b = "" },
                        new LanguageObject { Name = "Norwegian Nynorsk; Nynorsk, Norwegian", Abr2 ="nn", Abr3a = "nno", Abr3b = "" },
                        new LanguageObject { Name = "Norwegian", Abr2 ="no", Abr3a = "nor", Abr3b = "" },
                        new LanguageObject { Name = "Nubian languages", Abr2 ="", Abr3a = "nub", Abr3b = "" },
                        new LanguageObject { Name = "Nyamwezi", Abr2 ="", Abr3a = "nym", Abr3b = "" },
                        new LanguageObject { Name = "Nyankole", Abr2 ="", Abr3a = "nyn", Abr3b = "" },
                        new LanguageObject { Name = "Nyoro", Abr2 ="", Abr3a = "nyo", Abr3b = "" },
                        new LanguageObject { Name = "Nzima", Abr2 ="", Abr3a = "nzi", Abr3b = "" },
                        new LanguageObject { Name = "Occitan (post 1500)", Abr2 ="oc", Abr3a = "oci", Abr3b = "" },
                        new LanguageObject { Name = "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)", Abr2 ="", Abr3a = "arc", Abr3b = "" },
                        new LanguageObject { Name = "Ojibwa", Abr2 ="oj", Abr3a = "oji", Abr3b = "" },
                        new LanguageObject { Name = "Oriya", Abr2 ="or", Abr3a = "ori", Abr3b = "" },
                        new LanguageObject { Name = "Oromo", Abr2 ="om", Abr3a = "orm", Abr3b = "" },
                        new LanguageObject { Name = "Osage", Abr2 ="", Abr3a = "osa", Abr3b = "" },
                        new LanguageObject { Name = "Ossetian; Ossetic", Abr2 ="os", Abr3a = "oss", Abr3b = "" },
                        new LanguageObject { Name = "Otomian languages", Abr2 ="", Abr3a = "oto", Abr3b = "" },
                        new LanguageObject { Name = "Pahlavi", Abr2 ="", Abr3a = "pal", Abr3b = "" },
                        new LanguageObject { Name = "Palauan", Abr2 ="", Abr3a = "pau", Abr3b = "" },
                        new LanguageObject { Name = "Pali", Abr2 ="pi", Abr3a = "pli", Abr3b = "" },
                        new LanguageObject { Name = "Pampanga; Kapampangan", Abr2 ="", Abr3a = "pam", Abr3b = "" },
                        new LanguageObject { Name = "Pangasinan", Abr2 ="", Abr3a = "pag", Abr3b = "" },
                        new LanguageObject { Name = "Panjabi; Punjabi", Abr2 ="pa", Abr3a = "pan", Abr3b = "" },
                        new LanguageObject { Name = "Papiamento", Abr2 ="", Abr3a = "pap", Abr3b = "" },
                        new LanguageObject { Name = "Papuan languages", Abr2 ="", Abr3a = "paa", Abr3b = "" },
                        new LanguageObject { Name = "Pedi; Sepedi; Northern Sotho", Abr2 ="", Abr3a = "nso", Abr3b = "" },
                        new LanguageObject { Name = "Persian", Abr2 ="fa", Abr3a = "per", Abr3b = "fas" },
                        new LanguageObject { Name = "Persian, Old (ca.600-400 B.C.)", Abr2 ="", Abr3a = "peo", Abr3b = "" },
                        new LanguageObject { Name = "Philippine languages", Abr2 ="", Abr3a = "phi", Abr3b = "" },
                        new LanguageObject { Name = "Phoenician", Abr2 ="", Abr3a = "phn", Abr3b = "" },
                        new LanguageObject { Name = "Pohnpeian", Abr2 ="", Abr3a = "pon", Abr3b = "" },
                        new LanguageObject { Name = "Polish", Abr2 ="pl", Abr3a = "pol", Abr3b = "" },
                        new LanguageObject { Name = "Portuguese", Abr2 ="pt", Abr3a = "por", Abr3b = "" },
                        new LanguageObject { Name = "Prakrit languages", Abr2 ="", Abr3a = "pra", Abr3b = "" },
                        new LanguageObject { Name = "Provençal, Old (to 1500); Occitan, Old (to 1500)", Abr2 ="", Abr3a = "pro", Abr3b = "" },
                        new LanguageObject { Name = "Pushto; Pashto", Abr2 ="ps", Abr3a = "pus", Abr3b = "" },
                        new LanguageObject { Name = "Quechua", Abr2 ="qu", Abr3a = "que", Abr3b = "" },
                        new LanguageObject { Name = "Rajasthani", Abr2 ="", Abr3a = "raj", Abr3b = "" },
                        new LanguageObject { Name = "Rapanui", Abr2 ="", Abr3a = "rap", Abr3b = "" },
                        new LanguageObject { Name = "Rarotongan; Cook Islands Maori", Abr2 ="", Abr3a = "rar", Abr3b = "" },
                        new LanguageObject { Name = "Reserved for local use: qaa", Abr2 ="", Abr3a = "qaa", Abr3b = "" },
                        new LanguageObject { Name = "Reserved for local use: qad", Abr2 ="", Abr3a = "qad", Abr3b = "" },
                        new LanguageObject { Name = "Romance languages", Abr2 ="", Abr3a = "roa", Abr3b = "" },
                        //new LanguageObject { Name = "Romanian; Moldavian; Moldovan", Abr2 ="ro", Abr3a = "rum", Abr3b = "ron" },
                        new LanguageObject { Name = "Romansh", Abr2 ="rm", Abr3a = "roh", Abr3b = "" },
                        new LanguageObject { Name = "Romany", Abr2 ="", Abr3a = "rom", Abr3b = "" },
                        new LanguageObject { Name = "Rundi", Abr2 ="rn", Abr3a = "run", Abr3b = "" },
                        new LanguageObject { Name = "Russian", Abr2 ="ru", Abr3a = "rus", Abr3b = "" },
                        new LanguageObject { Name = "Salishan languages", Abr2 ="", Abr3a = "sal", Abr3b = "" },
                        new LanguageObject { Name = "Samaritan Aramaic", Abr2 ="", Abr3a = "sam", Abr3b = "" },
                        new LanguageObject { Name = "Sami languages", Abr2 ="", Abr3a = "smi", Abr3b = "" },
                        new LanguageObject { Name = "Samoan", Abr2 ="sm", Abr3a = "smo", Abr3b = "" },
                        new LanguageObject { Name = "Sandawe", Abr2 ="", Abr3a = "sad", Abr3b = "" },
                        new LanguageObject { Name = "Sango", Abr2 ="sg", Abr3a = "sag", Abr3b = "" },
                        new LanguageObject { Name = "Sanskrit", Abr2 ="sa", Abr3a = "san", Abr3b = "" },
                        new LanguageObject { Name = "Santali", Abr2 ="", Abr3a = "sat", Abr3b = "" },
                        new LanguageObject { Name = "Sardinian", Abr2 ="sc", Abr3a = "srd", Abr3b = "" },
                        new LanguageObject { Name = "Sasak", Abr2 ="", Abr3a = "sas", Abr3b = "" },
                        new LanguageObject { Name = "Scots", Abr2 ="", Abr3a = "sco", Abr3b = "" },
                        new LanguageObject { Name = "Selkup", Abr2 ="", Abr3a = "sel", Abr3b = "" },
                        new LanguageObject { Name = "Semitic languages", Abr2 ="", Abr3a = "sem", Abr3b = "" },
                        new LanguageObject { Name = "Serbian", Abr2 ="sr", Abr3a = "srp", Abr3b = "" },
                        new LanguageObject { Name = "Serer", Abr2 ="", Abr3a = "srr", Abr3b = "" },
                        new LanguageObject { Name = "Shan", Abr2 ="", Abr3a = "shn", Abr3b = "" },
                        new LanguageObject { Name = "Shona", Abr2 ="sn", Abr3a = "sna", Abr3b = "" },
                        new LanguageObject { Name = "Sichuan Yi; Nuosu", Abr2 ="ii", Abr3a = "iii", Abr3b = "" },
                        new LanguageObject { Name = "Sicilian", Abr2 ="", Abr3a = "scn", Abr3b = "" },
                        new LanguageObject { Name = "Sidamo", Abr2 ="", Abr3a = "sid", Abr3b = "" },
                        new LanguageObject { Name = "Sign Languages", Abr2 ="", Abr3a = "sgn", Abr3b = "" },
                        new LanguageObject { Name = "Siksika", Abr2 ="", Abr3a = "bla", Abr3b = "" },
                        new LanguageObject { Name = "Sindhi", Abr2 ="sd", Abr3a = "snd", Abr3b = "" },
                        new LanguageObject { Name = "Sinhala; Sinhalese", Abr2 ="si", Abr3a = "sin", Abr3b = "" },
                        new LanguageObject { Name = "Sino-Tibetan languages", Abr2 ="", Abr3a = "sit", Abr3b = "" },
                        new LanguageObject { Name = "Siouan languages", Abr2 ="", Abr3a = "sio", Abr3b = "" },
                        new LanguageObject { Name = "Skolt Sami", Abr2 ="", Abr3a = "sms", Abr3b = "" },
                        new LanguageObject { Name = "Slave (Athapascan)", Abr2 ="", Abr3a = "den", Abr3b = "" },
                        new LanguageObject { Name = "Slavic languages", Abr2 ="", Abr3a = "sla", Abr3b = "" },
                        new LanguageObject { Name = "Slovak", Abr2 ="sk", Abr3a = "slo", Abr3b = "slk" },
                        new LanguageObject { Name = "Slovenian", Abr2 ="sl", Abr3a = "slv", Abr3b = "" },
                        new LanguageObject { Name = "Sogdian", Abr2 ="", Abr3a = "sog", Abr3b = "" },
                        new LanguageObject { Name = "Somali", Abr2 ="so", Abr3a = "som", Abr3b = "" },
                        new LanguageObject { Name = "Songhai languages", Abr2 ="", Abr3a = "son", Abr3b = "" },
                        new LanguageObject { Name = "Soninke", Abr2 ="", Abr3a = "snk", Abr3b = "" },
                        new LanguageObject { Name = "Sorbian languages", Abr2 ="", Abr3a = "wen", Abr3b = "" },
                        new LanguageObject { Name = "Sotho, Southern", Abr2 ="st", Abr3a = "sot", Abr3b = "" },
                        new LanguageObject { Name = "South American Indian languages", Abr2 ="", Abr3a = "sai", Abr3b = "" },
                        new LanguageObject { Name = "Southern Altai", Abr2 ="", Abr3a = "alt", Abr3b = "" },
                        new LanguageObject { Name = "Southern Sami", Abr2 ="", Abr3a = "sma", Abr3b = "" },
                        new LanguageObject { Name = "Spanish; Castilian", Abr2 ="es", Abr3a = "spa", Abr3b = "" },
                        new LanguageObject { Name = "Sranan Tongo", Abr2 ="", Abr3a = "srn", Abr3b = "" },
                        new LanguageObject { Name = "Standard Moroccan Tamazight", Abr2 ="", Abr3a = "zgh", Abr3b = "" },
                        new LanguageObject { Name = "Sukuma", Abr2 ="", Abr3a = "suk", Abr3b = "" },
                        new LanguageObject { Name = "Sumerian", Abr2 ="", Abr3a = "sux", Abr3b = "" },
                        new LanguageObject { Name = "Sundanese", Abr2 ="su", Abr3a = "sun", Abr3b = "" },
                        new LanguageObject { Name = "Susu", Abr2 ="", Abr3a = "sus", Abr3b = "" },
                        new LanguageObject { Name = "Swahili", Abr2 ="sw", Abr3a = "swa", Abr3b = "" },
                        new LanguageObject { Name = "Swati", Abr2 ="ss", Abr3a = "ssw", Abr3b = "" },
                        new LanguageObject { Name = "Swedish", Abr2 ="sv", Abr3a = "swe", Abr3b = "" },
                        new LanguageObject { Name = "Swiss German; Alemannic; Alsatian", Abr2 ="", Abr3a = "gsw", Abr3b = "" },
                        new LanguageObject { Name = "Syriac", Abr2 ="", Abr3a = "syr", Abr3b = "" },
                        new LanguageObject { Name = "Tagalog", Abr2 ="tl", Abr3a = "tgl", Abr3b = "" },
                        new LanguageObject { Name = "Tahitian", Abr2 ="ty", Abr3a = "tah", Abr3b = "" },
                        new LanguageObject { Name = "Tai languages", Abr2 ="", Abr3a = "tai", Abr3b = "" },
                        new LanguageObject { Name = "Tajik", Abr2 ="tg", Abr3a = "tgk", Abr3b = "" },
                        new LanguageObject { Name = "Tamashek", Abr2 ="", Abr3a = "tmh", Abr3b = "" },
                        new LanguageObject { Name = "Tamil", Abr2 ="ta", Abr3a = "tam", Abr3b = "" },
                        new LanguageObject { Name = "Tatar", Abr2 ="tt", Abr3a = "tat", Abr3b = "" },
                        new LanguageObject { Name = "Telugu", Abr2 ="te", Abr3a = "tel", Abr3b = "" },
                        new LanguageObject { Name = "Tereno", Abr2 ="", Abr3a = "ter", Abr3b = "" },
                        new LanguageObject { Name = "Tetum", Abr2 ="", Abr3a = "tet", Abr3b = "" },
                        new LanguageObject { Name = "Thai", Abr2 ="th", Abr3a = "tha", Abr3b = "" },
                        new LanguageObject { Name = "Tibetan", Abr2 ="bo", Abr3a = "tib", Abr3b = "bod" },
                        new LanguageObject { Name = "Tigre", Abr2 ="", Abr3a = "tig", Abr3b = "" },
                        new LanguageObject { Name = "Tigrinya", Abr2 ="ti", Abr3a = "tir", Abr3b = "" },
                        new LanguageObject { Name = "Timne", Abr2 ="", Abr3a = "tem", Abr3b = "" },
                        new LanguageObject { Name = "Tiv", Abr2 ="", Abr3a = "tiv", Abr3b = "" },
                        new LanguageObject { Name = "Tlingit", Abr2 ="", Abr3a = "tli", Abr3b = "" },
                        new LanguageObject { Name = "Tok Pisin", Abr2 ="", Abr3a = "tpi", Abr3b = "" },
                        new LanguageObject { Name = "Tokelau", Abr2 ="", Abr3a = "tkl", Abr3b = "" },
                        new LanguageObject { Name = "Tonga (Nyasa)", Abr2 ="", Abr3a = "tog", Abr3b = "" },
                        new LanguageObject { Name = "Tonga (Tonga Islands)", Abr2 ="to", Abr3a = "ton", Abr3b = "" },
                        new LanguageObject { Name = "Tsimshian", Abr2 ="", Abr3a = "tsi", Abr3b = "" },
                        new LanguageObject { Name = "Tsonga", Abr2 ="ts", Abr3a = "tso", Abr3b = "" },
                        new LanguageObject { Name = "Tswana", Abr2 ="tn", Abr3a = "tsn", Abr3b = "" },
                        new LanguageObject { Name = "Tumbuka", Abr2 ="", Abr3a = "tum", Abr3b = "" },
                        new LanguageObject { Name = "Tupi languages", Abr2 ="", Abr3a = "tup", Abr3b = "" },
                        new LanguageObject { Name = "Turkish", Abr2 ="tr", Abr3a = "tur", Abr3b = "" },
                        new LanguageObject { Name = "Turkish, Ottoman (1500-1928)", Abr2 ="", Abr3a = "ota", Abr3b = "" },
                        new LanguageObject { Name = "Turkmen", Abr2 ="tk", Abr3a = "tuk", Abr3b = "" },
                        new LanguageObject { Name = "Tuvalu", Abr2 ="", Abr3a = "tvl", Abr3b = "" },
                        new LanguageObject { Name = "Tuvinian", Abr2 ="", Abr3a = "tyv", Abr3b = "" },
                        new LanguageObject { Name = "Twi", Abr2 ="tw", Abr3a = "twi", Abr3b = "" },
                        new LanguageObject { Name = "Udmurt", Abr2 ="", Abr3a = "udm", Abr3b = "" },
                        new LanguageObject { Name = "Ugaritic", Abr2 ="", Abr3a = "uga", Abr3b = "" },
                        new LanguageObject { Name = "Uighur; Uyghur", Abr2 ="ug", Abr3a = "uig", Abr3b = "" },
                        new LanguageObject { Name = "Ukrainian", Abr2 ="uk", Abr3a = "ukr", Abr3b = "" },
                        new LanguageObject { Name = "Umbundu", Abr2 ="", Abr3a = "umb", Abr3b = "" },
                        new LanguageObject { Name = "Uncoded languages", Abr2 ="", Abr3a = "mis", Abr3b = "" },
                        new LanguageObject { Name = "Undetermined", Abr2 ="", Abr3a = "und", Abr3b = "" },
                        new LanguageObject { Name = "Upper Sorbian", Abr2 ="", Abr3a = "hsb", Abr3b = "" },
                        new LanguageObject { Name = "Urdu", Abr2 ="ur", Abr3a = "urd", Abr3b = "" },
                        new LanguageObject { Name = "Uzbek", Abr2 ="uz", Abr3a = "uzb", Abr3b = "" },
                        new LanguageObject { Name = "Vai", Abr2 ="", Abr3a = "vai", Abr3b = "" },
                        new LanguageObject { Name = "Venda", Abr2 ="ve", Abr3a = "ven", Abr3b = "" },
                        new LanguageObject { Name = "Vietnamese", Abr2 ="vi", Abr3a = "vie", Abr3b = "" },
                        new LanguageObject { Name = "Volapük", Abr2 ="vo", Abr3a = "vol", Abr3b = "" },
                        new LanguageObject { Name = "Votic", Abr2 ="", Abr3a = "vot", Abr3b = "" },
                        new LanguageObject { Name = "Wakashan languages", Abr2 ="", Abr3a = "wak", Abr3b = "" },
                        new LanguageObject { Name = "Walloon", Abr2 ="wa", Abr3a = "wln", Abr3b = "" },
                        new LanguageObject { Name = "Waray", Abr2 ="", Abr3a = "war", Abr3b = "" },
                        new LanguageObject { Name = "Washo", Abr2 ="", Abr3a = "was", Abr3b = "" },
                        new LanguageObject { Name = "Welsh", Abr2 ="cy", Abr3a = "wel", Abr3b = "cym" },
                        new LanguageObject { Name = "Western Frisian", Abr2 ="fy", Abr3a = "fry", Abr3b = "" },
                        new LanguageObject { Name = "Wolaitta; Wolaytta", Abr2 ="", Abr3a = "wal", Abr3b = "" },
                        new LanguageObject { Name = "Wolof", Abr2 ="wo", Abr3a = "wol", Abr3b = "" },
                        new LanguageObject { Name = "Xhosa", Abr2 ="xh", Abr3a = "xho", Abr3b = "" },
                        new LanguageObject { Name = "Yakut", Abr2 ="", Abr3a = "sah", Abr3b = "" },
                        new LanguageObject { Name = "Yao", Abr2 ="", Abr3a = "yao", Abr3b = "" },
                        new LanguageObject { Name = "Yapese", Abr2 ="", Abr3a = "yap", Abr3b = "" },
                        new LanguageObject { Name = "Yiddish", Abr2 ="yi", Abr3a = "yid", Abr3b = "" },
                        new LanguageObject { Name = "Yoruba", Abr2 ="yo", Abr3a = "yor", Abr3b = "" },
                        new LanguageObject { Name = "Yupik languages", Abr2 ="", Abr3a = "ypk", Abr3b = "" },
                        new LanguageObject { Name = "Zande languages", Abr2 ="", Abr3a = "znd", Abr3b = "" },
                        new LanguageObject { Name = "Zapotec", Abr2 ="", Abr3a = "zap", Abr3b = "" },
                        new LanguageObject { Name = "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", Abr2 ="", Abr3a = "zza", Abr3b = "" },
                        new LanguageObject { Name = "Zenaga", Abr2 ="", Abr3a = "zen", Abr3b = "" },
                        new LanguageObject { Name = "Zhuang; Chuang", Abr2 ="za", Abr3a = "zha", Abr3b = "" },
                        new LanguageObject { Name = "Zulu", Abr2 ="zu", Abr3a = "zul", Abr3b = "" },
                        new LanguageObject { Name = "Zuni", Abr2 ="", Abr3a = "zun", Abr3b = "" },


                    };

        public static LanguageObject GetLanguageFromIdentifier(string str)
        {
            if (string.IsNullOrEmpty(str)) return null;

            switch (str.Length)
            {
                case 2:
                    return Iso639.FirstOrDefault(l => l.Abr2 == str);

                case 3:
                    return Iso639.FirstOrDefault(l => l.Abr3a == str || l.Abr3a == str);

                default:
                    return Iso639.FirstOrDefault(l => l.Name == str || l.Name.StartsWith(str));
            }
        }
    }

    public class LanguageObject
    {
        public string Name { get; set; }
        public string Abr2 { get; set; }
        public string Abr3a { get; set; }
        public string Abr3b { get; set; }

        public string Code
        {
            get
            {
                if (!string.IsNullOrEmpty(Abr2)) return Abr2;
                if (!string.IsNullOrEmpty(Abr3a)) return Abr3a;
                if (!string.IsNullOrEmpty(Abr3b)) return Abr3b;

                return Name;
            }
        }
    }

}
