//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//
// https://stackoverflow.com/questions/826777/how-to-have-an-auto-incrementing-version-number-visual-studio

using System.Reflection;

[assembly: AssemblyTitle("Movies Indexer")]
[assembly: AssemblyProduct("Movies Indexer")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("just me")]
[assembly: AssemblyCopyright("Copyright © 2016-2018 CalinM")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]


[assembly: AssemblyVersion("2.1.1510.3815")]
[assembly: AssemblyFileVersion("2.1.1510.3815")]