//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desene.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desene.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accessories_text_editor_icon {
            get {
                object obj = ResourceManager.GetObject("accessories-text-editor-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add2 {
            get {
                object obj = ResourceManager.GetObject("add2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addChange {
            get {
                object obj = ResourceManager.GetObject("addChange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowDown12 {
            get {
                object obj = ResourceManager.GetObject("arrowDown12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowRight12 {
            get {
                object obj = ResourceManager.GetObject("arrowRight12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bulkEdit {
            get {
                object obj = ResourceManager.GetObject("bulkEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calender_icon {
            get {
                object obj = ResourceManager.GetObject("calender-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckFileExistence {
            get {
                object obj = ResourceManager.GetObject("CheckFileExistence", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap combineNames {
            get {
                object obj = ResourceManager.GetObject("combineNames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap consumerism {
            get {
                object obj = ResourceManager.GetObject("consumerism", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///function RenderCollections(){
        ///    CloseSideNav();
        ///
        ///    var sectionHtml =
        ///        &quot;&lt;table id=\&quot;seriesHeaderTable\&quot; class=\&quot;tableWrapper\&quot;&gt;&quot; +
        ///        &quot;&lt;tr class=\&quot;headerRow\&quot;&gt;&quot; +
        ///        &quot;&lt;td style=\&quot;width: 30px;\&quot;&gt;&quot; +
        ///        &quot;&lt;div class=&apos;c-settings&apos; title=&apos;Options&apos;&gt;&lt;/div&gt;&quot; +
        ///        &quot;&lt;/td&gt;&quot; +
        ///        &quot;&lt;td&gt;&quot; +
        ///        &quot;Collection name&lt;/br&gt;/ Element title&quot; +
        ///        &quot;&lt;/td&gt;&quot; +
        ///        &quot;&lt;td class=\&quot;markerCol\&quot;&gt;&quot; +
        ///        &quot;&lt;/td&gt;&quot; +
        ///        &quot;&lt;td class=\&quot;detailCell w100\&quot;&gt;&quot; +
        ///        &quot;Recommen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cr_collectionsJS {
            get {
                return ResourceManager.GetString("cr_collectionsJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///    DisplayHome();
        ///    ResizeMoviesSection();
        ///
        ///    BindSearchEvents();
        ///    BindNavigationMenuEvents();
        ///});
        ///
        ///$(window).resize(function () {
        ///    //triggering the recalculation only when the resize has stop
        ///    waitForFinalEvent(function () {
        ///        ResizeMoviesSection();
        ///    }, 100, &quot;contentWrapper&quot;);
        ///
        ///    //setTimeout(function () { ResizeMoviesSection(); }, 100);
        ///});
        ///
        ///
        ///function BindSearchEvents() {
        ///	    $(&quot;#searchCtrl&quot;).on(&quot;focus&quot;, function () {
        ///        $( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cr_mainJS {
            get {
                return ResourceManager.GetString("cr_mainJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///function BuildMoviesGridSection() {
        ///	var sectionHtml =
        ///		&quot;&lt;div id=\&quot;jsGrid\&quot;&gt;&lt;/div&gt;&quot; +
        ///		&quot;&lt;div id=\&quot;jsGridPager\&quot;&gt;&quot; +
        ///		&quot;&lt;div style=\&quot;display:table-row;\&quot;&gt;&quot; +
        ///		&quot;&lt;div id=\&quot;pager-wrapper\&quot;&gt;&quot; +
        ///		&quot;&lt;/div&gt;&quot; +
        ///		&quot;&lt;div id=\&quot;pager-customOptions\&quot;&gt;&quot; +
        ///		&quot;&lt;div style=\&quot;display: inline-block;\&quot;&gt;&quot; +
        ///		&quot;Page size:&quot; +
        ///		&quot;&lt;/div&gt;&quot; +
        ///		&quot;&lt;div style=\&quot;display: inline-block; padding-left: 5px;\&quot;&gt;&quot; +
        ///		&quot;&lt;select id=\&quot;gridPageCount\&quot; onchange=\&quot;setPageCount()\&quot;&gt;&quot; +
        ///		&quot;&lt;option value=\&quot;10\&quot;&gt;10&lt;/option&gt;&quot; +
        ///		&quot;&lt;opti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cr_moviesJS {
            get {
                return ResourceManager.GetString("cr_moviesJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var currentSeriesTypeViewDataM;
        ///var currentSeriesTypeViewDataD;
        ///var showingSeries;
        ///
        ///function RenderSeriesTypeView() {
        ///    var sectionHtml;
        ///
        ///    if (isMobile())
        ///    {
        ///        sectionHtml =
        ///            &quot;&lt;div class=\&quot;container\&quot;&gt;&quot; +
        ///                &quot;&lt;div class=\&quot;cards\&quot;&gt;&quot;;
        ///
        ///        currentSeriesTypeViewDataM.forEach(function (el) {
        ///            sectionHtml +=
        ///                    &quot;&lt;div class=\&quot;cardM\&quot;&gt;&quot; +
        ///                        &quot;&lt;div class=\&quot;movie-detail-wrapper\&quot; data-movieId=\&quot;&quot; + el.Id + &quot;\&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cr_seriesJS {
            get {
                return ResourceManager.GetString("cr_seriesJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var trailerPlaying = false;
        ///var searchResultTimer = null;
        ///
        ///var waitForFinalEvent = (function () {
        ///    var timers = {};
        ///    return function (callback, ms, uniqueId) {
        ///        if (!uniqueId) {
        ///            uniqueId = &quot;Don&apos;t call this twice without a uniqueId&quot;;
        ///        }
        ///        if (timers[uniqueId]) {
        ///            clearTimeout(timers[uniqueId]);
        ///        }
        ///        timers[uniqueId] = setTimeout(callback, ms);
        ///    };
        ///})();
        ///
        ///function DisplayHome() {
        ///	SoftCloseSearch();
        ///
        ///	$(&quot;#moviesSections&quot;).css( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cr_sharedJS {
            get {
                return ResourceManager.GetString("cr_sharedJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csm_recommended_age {
            get {
                object obj = ResourceManager.GetObject("csm_recommended_age", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///html, body {
        ///    padding: 0;
        ///    margin: 0;
        ///    height: 100%;
        ///    width: 100%;
        ///}
        ///
        ///.master-toolbar {
        ///    display: table;
        ///    width: 100%;
        ///    background-color: rgba(91,21,71,1);
        ///    height: 75px;
        ///}
        ///
        ///.master-toolbar-row {
        ///    display: table-row;
        ///}
        ///
        ///.vertical-menu-button-wrapper {
        ///    display: table-cell;
        ///    width: 75px;
        ///    vertical-align: middle;
        ///    text-align: center;
        ///}
        ///
        ///.menu-button {
        ///    font-size: 36px;
        ///    width: 30px;
        ///    height: 0.125em;
        ///    border-top: 0.375em double  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string deseneCSS {
            get {
                return ResourceManager.GetString("deseneCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drinking_druge_smoking {
            get {
                object obj = ResourceManager.GetObject("drinking_druge_smoking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap educational_value {
            get {
                object obj = ResourceManager.GetObject("educational_value", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap external_icon {
            get {
                object obj = ResourceManager.GetObject("external-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FullHD_logo {
            get {
                object obj = ResourceManager.GetObject("FullHD_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generateHtml {
            get {
                object obj = ResourceManager.GetObject("generateHtml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generatePdf {
            get {
                object obj = ResourceManager.GetObject("generatePdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD_logo {
            get {
                object obj = ResourceManager.GetObject("HD_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_download_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-download-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_external_link_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-external-link-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_external_link_24 {
            get {
                object obj = ResourceManager.GetObject("icons8-external-link-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Cartoons Repository&lt;/title&gt;
        ///
        ///&lt;link rel=&quot;shortcut icon&quot; href=&quot;Images\mickey_mouse.png&quot;&gt;
        ///
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css?family=Mouse+Memoirs&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css?family=Mountains [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info1 {
            get {
                object obj = ResourceManager.GetObject("info1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info2 {
            get {
                object obj = ResourceManager.GetObject("info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.2.4 | (c) jQuery Foundation | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m=&quot;2.2.4&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+|[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_2_4_min {
            get {
                return ResourceManager.GetString("jquery_2_2_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset &quot;UTF-8&quot;;/*!
        /// * jQuery contextMenu - Plugin for simple contextMenu handling
        /// *
        /// * Version: v2.9.2
        /// *
        /// * Authors: Björn Brala (SWIS.nl), Rodney Rehm, Addy Osmani (patches for FF)
        /// * Web: http://swisnl.github.io/jQuery-contextMenu/
        /// *
        /// * Copyright (c) 2011-2020 SWIS BV and contributors
        /// *
        /// * Licensed under
        /// *   MIT License http://www.opensource.org/licenses/mit-license
        /// *
        /// * Date: 2020-05-13T13:55:37.023Z
        /// */@-webkit-keyframes cm-spin{0%{-webkit-transform:translateY(-50%) rotate(0);trans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_contextMenu_minCSS {
            get {
                return ResourceManager.GetString("jquery_contextMenu_minCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(e){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],e):&quot;object&quot;==typeof exports?e(require(&quot;jquery&quot;)):e(jQuery)}(function(m){&quot;use strict&quot;;var a;m.support.htmlMenuitem=&quot;HTMLMenuItemElement&quot;in window,m.support.htmlCommand=&quot;HTMLCommandElement&quot;in window,m.support.eventSelectstart=&quot;onselectstart&quot;in document.documentElement,m.ui&amp;&amp;m.widget||(m.cleanData=(a=m.cleanData,function(e){var t,n,o;for(o=0;null!=e[o];o++){n=e[o];try{(t=m._data(n,&quot;events&quot;))&amp;&amp;t.remove&amp;&amp;m(n).triggerHandler(&quot;remove&quot;)}catch(e){} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_contextMenu_minJS {
            get {
                return ResourceManager.GetString("jquery_contextMenu_minJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery &amp; Zepto Lazy v1.7.5 - http://jquery.eisbehr.de/lazy - MIT&amp;GPL-2.0 license - Copyright 2012-2017 Daniel &apos;Eisbehr&apos; Kern */
        ///!function(t,e){&quot;use strict&quot;;function r(r,a,i,l,u){function f(){L=t.devicePixelRatio&gt;1,c(i),a.delay&gt;=0&amp;&amp;setTimeout(function(){s(!0)},a.delay),(a.delay&lt;0||a.combined)&amp;&amp;(l.e=v(a.throttle,function(t){&quot;resize&quot;===t.type&amp;&amp;(w=B=-1),s(t.all)}),l.a=function(t){c(t),i.push.apply(i,t)},l.g=function(){return i=n(i).filter(function(){return!n(this).data(a.loadedName)})},l.f=function(t){for( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_lazy_min {
            get {
                return ResourceManager.GetString("jquery_lazy_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Copyright (c) 2011 Piotr Rochala (http://rocha.la)
        /// * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
        /// * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
        /// *
        /// * Version: 1.3.8
        /// *
        /// */
        ///(function($) {
        ///
        ///    $.fn.extend({
        ///      slimScroll: function(options) {
        ///  
        ///        var defaults = {
        ///  
        ///          // width in pixels of the visible scroll area
        ///          width : &apos;auto&apos;,
        ///  
        ///          // height in pixels of the visible scroll area
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_slimscroll_min {
            get {
                return ResourceManager.GetString("jquery_slimscroll_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.12.1 - 2016-09-16
        /// * http://jqueryui.com
        /// * Includes: position.js
        /// * Copyright jQuery Foundation and other contributors; Licensed MIT */
        ///
        ///(function(t){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],t):t(jQuery)})(function(t){t.ui=t.ui||{},t.ui.version=&quot;1.12.1&quot;,function(){function e(t,e,i){return[parseFloat(t[0])*(u.test(t[0])?e/100:1),parseFloat(t[1])*(u.test(t[1])?i/100:1)]}function i(e,i){return parseInt(t.css(e,i),10)||0}function s(e){var i=e[0];return 9===i.nodeType?{wid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_position_minJS {
            get {
                return ResourceManager.GetString("jquery_ui_position_minJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jsGrid v1.5.3 (http://js-grid.com)
        /// * (c) 2016 Artem Tabalin
        /// * Licensed under MIT (https://github.com/tabalinas/jsgrid/blob/master/LICENSE)
        /// */
        ///
        ///.jsgrid{position:relative;overflow:hidden;font-size:1em}.jsgrid,.jsgrid *,.jsgrid :after,.jsgrid :before{box-sizing:border-box}.jsgrid input,.jsgrid select,.jsgrid textarea{font-size:1em}.jsgrid-grid-header{overflow-x:hidden;overflow-y:scroll;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsgrid_minCSS {
            get {
                return ResourceManager.GetString("jsgrid_minCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jsGrid v1.5.3 (http://js-grid.com)
        /// * (c) 2016 Artem Tabalin
        /// * Licensed under MIT (https://github.com/tabalinas/jsgrid/blob/master/LICENSE)
        /// */
        ///
        ///!function(a,b,c){function d(a,c){var d=b(a);d.data(f,this),this._container=d,this.data=[],this.fields=[],this._editingRow=null,this._sortField=null,this._sortOrder=i,this._firstDisplayingPage=1,this._init(c),this.render()}var e=&quot;JSGrid&quot;,f=e,g=&quot;JSGridItem&quot;,h=&quot;JSGridEditRow&quot;,i=&quot;asc&quot;,j=&quot;desc&quot;,k=&quot;{first}&quot;,l=&quot;{pages}&quot;,m=&quot;{prev}&quot;,n=&quot;{next}&quot;,o=&quot;{last}&quot;,p=&quot;{pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsgrid_minJS {
            get {
                return ResourceManager.GetString("jsgrid_minJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jsGrid v1.5.3 (http://js-grid.com)
        /// * (c) 2016 Artem Tabalin
        /// * Licensed under MIT (https://github.com/tabalinas/jsgrid/blob/master/LICENSE)
        /// */
        ///
        ///.jsgrid-edit-row&gt;.jsgrid-cell,.jsgrid-filter-row&gt;.jsgrid-cell,.jsgrid-grid-body,.jsgrid-grid-header,.jsgrid-header-row&gt;.jsgrid-header-cell,.jsgrid-insert-row&gt;.jsgrid-cell{border:1px solid #e9e9e9}.jsgrid-header-row&gt;.jsgrid-header-cell{border-top:0}.jsgrid-filter-row&gt;.jsgrid-cell,.jsgrid-header-row&gt;.jsgrid-header-cell,.jsgrid-insert-row&gt;.jsgrid-cell{bor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsgrid_theme_min {
            get {
                return ResourceManager.GetString("jsgrid_theme_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mickey_mouse {
            get {
                object obj = ResourceManager.GetObject("mickey_mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] movies_index {
            get {
                object obj = ResourceManager.GetObject("movies_index", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap moviesList {
            get {
                object obj = ResourceManager.GetObject("moviesList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msg {
            get {
                object obj = ResourceManager.GetObject("msg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nav_icon {
            get {
                object obj = ResourceManager.GetObject("nav_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Owl Carousel v2.3.4
        /// * Copyright 2013-2018 David Deutsch
        /// * Licensed under: SEE LICENSE IN https://github.com/OwlCarousel2/OwlCarousel2/blob/master/LICENSE
        /// */
        ///.owl-carousel,.owl-carousel .owl-item{-webkit-tap-highlight-color:transparent;position:relative}.owl-carousel{display:none;width:100%;z-index:1}.owl-carousel .owl-stage{position:relative;-ms-touch-action:pan-Y;touch-action:manipulation;-moz-backface-visibility:hidden}.owl-carousel .owl-stage:after{content:&quot;.&quot;;display:block;clear:both;visi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string owl_carousel_minCSS {
            get {
                return ResourceManager.GetString("owl_carousel_minCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Owl Carousel v2.3.4
        /// * Copyright 2013-2018 David Deutsch
        /// * Licensed under: SEE LICENSE IN https://github.com/OwlCarousel2/OwlCarousel2/blob/master/LICENSE
        /// */
        ///!function(a,b,c,d){function e(b,c){this.settings=null,this.options=a.extend({},e.Defaults,c),this.$element=a(b),this._handlers={},this._plugins={},this._supress={},this._current=null,this._speed=null,this._coordinates=[],this._breakpoint=null,this._width=null,this._items=[],this._clones=[],this._mergers=[],this._widths=[],this._invalidate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string owl_carousel_minJS {
            get {
                return ResourceManager.GetString("owl_carousel_minJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pixel {
            get {
                object obj = ResourceManager.GetObject("pixel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plugin {
            get {
                object obj = ResourceManager.GetObject("Plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap positive_messages {
            get {
                object obj = ResourceManager.GetObject("positive_messages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap positive_role_models {
            get {
                object obj = ResourceManager.GetObject("positive_role_models", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preloader {
            get {
                object obj = ResourceManager.GetObject("preloader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reset {
            get {
                object obj = ResourceManager.GetObject("Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reset_slide {
            get {
                object obj = ResourceManager.GetObject("reset_slide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search1 {
            get {
                object obj = ResourceManager.GetObject("search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///html, body {
        ///    padding: 0;
        ///    margin: 0;
        ///    height: 100%;
        ///    width: 100%;
        ///}
        ///
        ///* {
        ///    -moz-transition-property: background-color, border-color, box-shadow, color, opacity, text-shadow, -moz-transform;
        ///    -o-transition-property: background-color, border-color, box-shadow, color, opacity, text-shadow, -o-transform;
        ///    -webkit-transition-property: background-color, border-color, box-shadow, color, opacity, text-shadow, -webkit-transform;
        ///    transition-property: background-color, border-colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sections {
            get {
                return ResourceManager.GetString("sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings16_h {
            get {
                object obj = ResourceManager.GetObject("settings16_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings16_n {
            get {
                object obj = ResourceManager.GetObject("settings16_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings24_n {
            get {
                object obj = ResourceManager.GetObject("settings24_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sexy_stuff {
            get {
                object obj = ResourceManager.GetObject("sexy_stuff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort {
            get {
                object obj = ResourceManager.GetObject("sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumbnail {
            get {
                object obj = ResourceManager.GetObject("thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap violence {
            get {
                object obj = ResourceManager.GetObject("violence", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap www {
            get {
                object obj = ResourceManager.GetObject("www", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset &quot;UTF-8&quot;;
        ///
        ////*
        ///    Name: YouTubePopUp
        ///    Description: jQuery plugin to display YouTube or Vimeo video in PopUp, responsive and retina, easy to use.
        ///    Version: 1.0.2
        ///    Plugin URL: http://wp-time.com/youtube-popup-jquery-plugin/
        ///    Written By: Qassim Hassan
        ///    Twitter: @QQQHZ
        ///    Websites: wp-time.com | qass.im | wp-plugins.in
        ///    Dual licensed under the MIT and GPL licenses:
        ///        http://www.opensource.org/licenses/mit-license.php
        ///        http://www.gnu.org/licenses/gpl.html
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouTubePopUp {
            get {
                return ResourceManager.GetString("YouTubePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///    Name: YouTubePopUp
        ///    Description: jQuery plugin to display YouTube or Vimeo video in PopUp, responsive and retina, easy to use.
        ///    Version: 1.0.2
        ///    Plugin URL: http://wp-time.com/youtube-popup-jquery-plugin/
        ///    Written By: Qassim Hassan
        ///    Twitter: @QQQHZ
        ///    Websites: wp-time.com | qass.im | wp-plugins.in
        ///    Dual licensed under the MIT and GPL licenses:
        ///        http://www.opensource.org/licenses/mit-license.php
        ///        http://www.gnu.org/licenses/gpl.html
        ///    Copyright (c) 2016 -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouTubePopUp_jquery {
            get {
                return ResourceManager.GetString("YouTubePopUp_jquery", resourceCulture);
            }
        }
    }
}
